msg = input('Digite algo: ')
print('O tipo primitivo é: ',type(msg))
print('É númerico ?', msg.isnumeric())
print('É Alfanumérico ?', msg.isalnum())
print('É primitivo Ascii', msg.isascii())
print('É decimal?', msg.isdecimal())
print('É Minúcula?', msg.islower())
print('É Maiúscula?',msg.isupper())
print('É um título?',msg.istitle())
