nmr = int(input('Digite um número para ver sua tabuada : '))
print('= '*6, 'Tabuada', '= '*6)
print('{} x {} = {}'.format(nmr, 1, nmr*1))
print('{} x {} = {}'.format(nmr, 2, nmr*2))
print('{} x {} = {}'.format(nmr, 3, nmr*3))
print('{} x {} = {}'.format(nmr, 4, nmr*4))
print('{} x {} = {}'.format(nmr, 5, nmr*5))
print('{} x {} = {}'.format(nmr, 6, nmr*6))
print('{} x {} = {}'.format(nmr, 7, nmr*7))
print('{} x {} = {}'.format(nmr, 8, nmr*8))
print('{} x {} = {}'.format(nmr, 9, nmr*9))
print('{} x {} = {}'.format(nmr, 10, nmr*10))
print('= '*6, 'Tabuada', '= '*6)
